### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [Kanahiro/MBStyleGenerator#1]
# Problem

Please change the homepage link to show your repo, not all the repos you own.
Also please remove the __pycache folder

**Comment by Kanahiro** [comment]
Thank you for reviewing, I've fixed two problems please check it.

**Comment by Kanahiro** [comment]
Fix exlib problem also and re-upload archive.

**Comment by Kanahiro** [comment]
I found problem and I have rejected approval, excuse me.
